[versions]
accompanistPermissions = "0.37.3"
coreKtx = "1.16.0"
kotlin = "2.2.0"
compose = "1.8.2"
agp = "8.10.1"
androidx-activityCompose = "1.10.1"
androidx-uiTest = "1.8.3"
kotlinxDatetime = "0.7.0"
maven-publish = "0.33.0"
kpermissions = "1.1.0"
gson = "2.13.1"
kotlinxCoroutinesCore = "1.10.2"
startupRuntime = "1.2.0"




[libraries]

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kpermissions = { module = "io.github.the-best-is-best:KPermissions", version.ref = "kpermissions" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startupRuntime" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
