[versions]
coreKtx = "1.15.0"
kotlin = "2.1.20"
compose = "1.7.3"
agp = "8.7.1"
androidx-activityCompose = "1.10.1"
androidx-uiTest = "1.7.8"
kotlinxDatetime = "0.6.2"
maven-publish = "0.30.0"
kpermissions = "1.1.0"
gson = "2.11.0"
kotlinxCoroutinesCore = "1.10.1"




[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kpermissions = { module = "io.github.the-best-is-best:KPermissions", version.ref = "kpermissions" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
